version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    restart: always
    command: redis-server /usr/local/conf/redis.conf

  db:
    image: mysql:8.0.37
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD : 1234
      MYSQL_DATABASE: movie
    ports:
      - "3306:3306"
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - ./database/mysql/init:/docker-entrypoint-initdb.d


